language: node_js
node_js: '12'
install: yarn bootstrap
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn stage; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn build; fi'
deploy:
  skip_cleanup: true
  provider: script
  script: yarn deploy-pinata
  on:
    branch: master
